[package]
name = "usrlib_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy_system_allocator = "0.8.0"
bitflags = "1.3.2"

[build-dependencies]
chrono = "0.4"
csv = "1.1.6"